Greenmark/Greenmark/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from home import views

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('',views.home_view,name='home'),
                  path('portfolio/',include('portfolio.urls')),
                  path('blog/', include('blog.urls')),
                  path('contactus/', include('contactus.urls')),
                  path('ckeditor/', include('ckeditor_uploader.urls')),

              ]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
admin.site.site_header = 'Admin Panel'


Greenmark/blog/urls.py
from django.urls import path, re_path
from .import views
app_name = 'blog'
urlpatterns = [
path('', views.bloggrid_view,name='grid'),
path('<str:Url>/', views.article_details, name='detail'),
]

Greenmark/contactus/urls.py
from django.urls import path, re_path
from .import views
app_name = 'contactus'
urlpatterns = [
path('', views.contact_view,name='reach'),

]

Greenmark/portfolio/urls.py
from django.urls import path, re_path
from .import views
app_name = 'allport'
urlpatterns = [
path('', views.portfolio_view,name='Portfolio'),
path('<str:title>/', views.portfoilo_details, name='portdetail'),
]

Greenmark/blog/models.py
from django.db import models
from django.utils.html import format_html
from ckeditor.fields import RichTextField




# Create your models here.
class Blog_grid(models.Model):
    Url = models.CharField(max_length=255,primary_key=True)
    title = models.CharField(max_length=100,unique=True)
    description = models.TextField()
    image = models.ImageField(default="default.png",blank=True,upload_to='category/')
    add_date = models.DateTimeField(auto_now_add=True, null=True)
    author = models.CharField(max_length=50, default=None)
    category = models.CharField(max_length=50, default=None)





    def __str__(self):
        return self.Url

    def snippet(self):
        return self.description[:150]+ "..."


    def day(self):
        return self.add_date.strftime('%d')
    def month(self):
        return self.add_date.strftime('%b')
    def year(self):
        return self.add_date.strftime('%Y')




class Blog_details(models.Model):
    Url = models.ForeignKey(Blog_grid, on_delete=models.CASCADE, related_name="Urls")
    content = RichTextField()
    quote=models.TextField()
    quoteauthor=models.CharField(max_length=100)
    othimage = models.ImageField(default="default.png",blank=True,upload_to='post/')
    authorpic=models.ImageField(default="default.png",blank=True,upload_to='post/')
    aboutauthor=models.TextField()
    fb_url=models.CharField(max_length=255,default=None)
    t_url=models.CharField(max_length=255,default=None)
    insta_url=models.CharField(max_length=255,default=None)





















Greenmark/contactus/models.py
from django.db import models

# Create your models here.
class Contact(models.Model):
    name = models.CharField(max_length=100)
    email = models.CharField(max_length=50, default=None)
    phonenumber = models.CharField(max_length=10)
    message = models.TextField()

    def __str__(self):
        return self.name



Greenmark/home/models.py
from django.db import models

class Grid(models.Model):
    title = models.CharField(max_length=100, unique=True)
    image = models.ImageField(default="default.png", blank=True, upload_to='grid/')
    category = models.CharField(max_length=50)

    def __str__(self):
        return self.title

    

Greenmark/portfolio/models.py
from django.db import models
from home.models import Grid
from ckeditor.fields import RichTextField


# Create your models here.
class PortfolioDetails(models.Model):

    image = models.ImageField(default="default.png", blank=True, upload_to='grid/')
    content = RichTextField()
    Mainimage = models.ImageField(default="default.png", blank=True, upload_to='grid/')
    image1 = models.ImageField(default="default.png", blank=True, upload_to='grid/')
    image2 = models.ImageField(default="default.png", blank=True, upload_to='grid/')
    image3 = models.ImageField(default="default.png", blank=True, upload_to='grid/')
    image4 = models.ImageField(default="default.png", blank=True, upload_to='grid/')
    image5 = models.ImageField(default="default.png", blank=True, upload_to='grid/')
    image6 = models.ImageField(default="default.png", blank=True, upload_to='grid/')
    title = models.ForeignKey(Grid, on_delete=models.CASCADE)

Greenmark/blog/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import Blog_grid,Blog_details
from django.core.paginator import Paginator
# Create your views here.

def bloggrid_view(request):
    articles = Blog_grid.objects.all().order_by('add_date')
    p=Paginator(Blog_grid.objects.all(),6)
    page=request.GET.get('page')
    blogs_grid=p.get_page(page)
    return render(request, 'blog/Blog.html', {'articles': articles,'blogs_grid':blogs_grid})
def article_details(request,Url):
    # return HttpResponse(slug)
    BLOG = Blog_details.objects.get(Url=Url)

    related=Blog_grid.objects.filter(category=BLOG.Url.category).exclude(Url=Url)

    return render(request, 'blog/blogdetails.html', {'BLOG': BLOG,'related':related})

Greenmark/contactus/views.py
from django.shortcuts import render
from .models import Contact
from django.core.mail import send_mail,BadHeaderError
from django.http import HttpResponse,HttpResponseRedirect
def contact_view(request):
    msg = {
        "status": "success"
    }
    if request.method == "POST":
        cont = Contact()
        name = request.POST.get('name')
        email = request.POST.get('email')
        phonenumber = request.POST.get('phonenumber')
        message=request.POST.get('message')
        cont.name=name
        cont.email=email
        cont.phonenumber=phonenumber
        cont.message=message
        cont.save()
        subject = "Website Inquiry"
        body = {
            'name': name,
            'phonenumber': phonenumber,
            'email': email,
            'message': message,
        }
        MESSAGE= "\n".join(body.values())
        try:
            send_mail(
                subject,
                MESSAGE,
                'hellocrys6@gmail.com',
                ['sarahcrystal21@gmail.com']
            )
            msg["status"] = "success"
        except BadHeaderError:
            return HttpResponse('Invalid header found.')
        return HttpResponseRedirect('/contactus/',msg)


    return render(request, 'contactus/Contactus.html',msg)

Greenmark/home/views.py
from django.shortcuts import render
from .models import Grid
from contactus.models import Contact
from django.core.mail import send_mail,BadHeaderError
def home_view(request):
    imgs = Grid.objects.all().order_by('?')[:6]
    if request.method == "POST":
        cont = Contact()
        name = request.POST.get('name')
        email = request.POST.get('email')
        phonenumber = request.POST.get('phonenumber')
        message=request.POST.get('message')
        cont.name=name
        cont.email=email
        cont.phonenumber=phonenumber
        cont.message=message
        cont.save()
        subject = "Website Inquiry"
        body = {
            'name': name,
            'phonenumber': phonenumber,
            'email':  email,
            'message':  message,
        }
        MESSAGE = "\n".join(body.values())
        send_mail(
            subject,
            MESSAGE,
            'hellocrys6@gmail.com',
            ['sarahcrystal21@gmail.com']
        )
    return render(request, 'home/Portfolio.html',{'imgs':imgs})

Greenmark/portfolio/views.py
from django.shortcuts import render
from home.models import Grid
from portfolio.models import PortfolioDetails

# Create your views here.
def portfolio_view(request):
    AllImages=Grid.objects.all()
    return render(request, 'portfolio/allportfolio.html',{'AllImages':AllImages})

def portfoilo_details(request,title):
   portdet=PortfolioDetails.objects.get(title__title=title)
   imgs = Grid.objects.all().order_by('?')[:6]
   return render(request, 'portfolio/portfolio-details.html', {'portdet':portdet,'imgs':imgs})


Greenmark/blog/templates/blog/Blog.html
{% extends 'base_layout.html' %}
{% load static %}
{% block content %}

<div class="slidearea bannerside">
			<div class="side-contact-info">
				<ul>
					<li><i class="fas fa-phone-alt"></i> +91 123 456 7890</li>
					<li><i class="fas fa-envelope"></i> Visvainfo@gmail.com</li>
				</ul>
			</div>
			<div class="dz-bnr-inr style-1 overlay-left" style="background-image: url({% static 'images/banner/bnr1.jpg' %});">
				<div class="container-fluid">
					<div class="dz-bnr-inr-entry">
						<h1>Our Blog</h1>
						<!-- Breadcrumb Row -->
						<nav aria-label="breadcrumb" class="breadcrumb-row">
							<ul class="breadcrumb">
								<li class="breadcrumb-item"><a href="index-2.html">Home</a></li>
								<li class="breadcrumb-item">Our Blog</li>
							</ul>
						</nav>
						<!-- Breadcrumb Row End -->
					</div>
				</div>
			</div>
		</div>
		<!-- Banner End -->
		<!-- Blog Large -->

<div class="content-inner">
	<div class="container">
		<div class="row ">
		  {% for article in blogs_grid %}
		   <div class="col-xl-4 col-md-6 col-sm-6 d-flex align-items-stretch card-container">
				<div class="dz-card blog-grid style-1 m-b50 aos-item w-100" data-aos="fade-up" data-aos-duration="1000" data-aos-delay="200">
					<div class="dz-media ">
						<a href="{% url 'blog:detail' article.Url %}"><img src="{{article.image.url}}" alt="" style="max-height:250px"></a>
					</div>
					<div class="dz-info">
						<div class="dz-meta">
							<ul>
								<li class="post-date">
									<strong>{{article.day}}</strong>
									<span>{{article.month}}</span>
								</li>
								<li class="post-category"><a href="javascript:void(0);" rel="category tag">Blog</a></li>
								<li class="post-user">By <a href="javascript:void(0);">{{article.author}}</a>
								</li>
							</ul>
						</div>
						<h3 class="dz-title"><a href="{% url 'blog:detail' article.Url %}">{{article.title}}</a></h3>
						<div class="dz-post-text text">
							<p>{{article.snippet}}</p>
						</div>
						<div class="read-more">
							<a href="{% url 'blog:detail' article.Url %}" class="btn btn-primary btn-rounded btn-sm hover-icon">
								<span>Read More </span>
								<i class="fas fa-arrow-right"></i>
							</a>
						</div>
					</div>
				</div>
		   </div>
		   {% endfor %}
		 </div>
         <div class="row">
			<div class="col-xl-12 col-lg-12">
				<nav aria-label="Blog Pagination">
					{% if blogs_grid.has_other_pages %}
					<ul class="pagination text-center m-b30">
                        {% if blogs_grid.has_previous %}

						<li class="page-item"><a class="page-link prev" href="?page={{ blogs_grid.previous_page_number }}"><i class="la la-angle-left"></i></a></li>
						{% else %}
						<li class="page-item disabled">
						{% endif %}
						{% for i in blogs_grid.paginator.page_range %}
						{% if blogs_grid.number == i %}
						<li class="page-item active"><a class="page-link" >{{i}}</a></li>
						{% else %}
						<li class="page-item "><a class="page-link" href="?page={{i}}">{{i}}</a>
						{% endif %}
						{% endfor %}
						{% if blogs_grid.has_next %}
						<li class="page-item"><a class="page-link next" href="?page={{ blogs_grid.next_page_number }}"><i class="la la-angle-right"></i></a></li>

						{% else %}
						<li class="page-item disabled">
						{% endif %}
					</ul>
					{% endif %}
				</nav>
			</div>
		</div>
	 </div>
</div>
{% endblock %}

Greenmark/blog/templates/blog/blogdetails.html
{% extends 'base_layout.html' %}
{% load static %}
{% load social_share %}
{% block content %}
   <div class="content-inner">
		<div class="container">
				<div class="row ">
					<h1 class="dz-title">{{BLOG.Url.title}}</h1>
					<div class="dz-meta">
						<ul>
							<li>{{BLOG.Url.day}}-{{BLOG.Url.month}}-{{BLOG.Url.year}}</li>
							<li class="post-user">By <a href="javascript:void(0);">{{BLOG.Url.author}}</a></li>
						</ul>
					</div>
					<div class="col-xl-12 col-lg-12 ">
						<div class="dz-card blog-single style-1">
							<div class="dz-media">
								<img src="{{BLOG.Url.image.url}}" style="height:720px" alt="">
							</div>
							<div class="dz-info">
								<div class="dz-post-text">

									<blockquote class="block-quote style-1">
										<p> {{BLOG.quote}}</p>
										<cite>{{BLOG.quoteauthor}}</cite>
									</blockquote>
									<div class="alignleft w-50">
										<img alt="" src="{{BLOG.othimage.url}}" class="w-100"/>
									</div>
									<p>{{BLOG.content|safe}}</p>

								</div>
								<div class="post-footer">
									<div class="post-tags">
										<strong>Tags:</strong>
										<a href="javascript:void(0);" rel="tag">{{BLOG.Url.category}}</a>
									</div>
									<div class="dz-share-post">
										<h5 class="title">Share :</h5>
										<ul class="dz-social-icon">

                                            <li><a class="fab fa-facebook-f" href="https://www.facebook.com/sharer/sharer.php?u={{  request.build_absolute_uri  }}" target="_blank"></a></li>
											<li><a class="fab fa-twitter" href="https://twitter.com/home?status=Read%20the%20latest%20blog%20now!{{  request.build_absolute_uri  }}" target="_blank"></a></li>
											<li><a class="fab fa-linkedin" href="https://www.linkedin.com/shareArticle?url = {{  request.build_absolute_uri  }} " target="_blank"></a></li>

										</ul>
									</div>
								</div>
							</div>
						</div>
						<!-- blog start -->
						<div class="author-box blog-user m-b60">
							<div class="author-profile-info">
								<div class="author-profile-pic">
									<img src="{{BLOG.authorpic.url}}" alt="Profile Pic">
								</div>
								<div class="author-profile-content">
									<h6>{{BLOG.Url.author}}</h6>
									<p>{{BLOG.aboutauthor}}
									<ul class="list-inline m-b0">
										<li>
											<a href="{{BLOG.insta_url}}" target="_blank" class="btn-link">
												<i class="fab fa-instagram"></i>
											</a>
										</li>
										<li>
											<a href="{{BLOG.fb_url}}" target="_blank" class="btn-link">
												<i class="fab fa-facebook-f"></i>
											</a>
										</li>
										<li>
											<a href="{{BLOG.t_url}}" target="_blank" class="btn-link">
												<i class="fab fa-twitter"></i>
											</a>
										</li>

									</ul>
								</div>
							</div>
						</div>
						<!-- Related Blogs -->

						<div class="row extra-blog style-1">
							<div class="col-md-12">
								<div class="widget-title">
									<h4 class="title"> Related Blogs</h4>
									<div class="dz-separator style-1 text-primary mb-0"></div>
								</div>
							</div>
							<div class="row ">
                               {% for article in related%}
								<div class="col-xl-4 col-md-6 col-sm-6  d-flex align-items-stretch card-container ">
									<div class="dz-card blog-grid style-1 m-b50 aos-item w-100" data-aos="fade-up" data-aos-duration="1000" data-aos-delay="200">
										<div class="dz-media">
											<a href="{% url 'blog:detail' article.Url %}"><img src="{{article.image.url}}" style="max-height:250px;"alt=""></a>
										</div>
										<div class="dz-info">
											<div class="dz-meta">
												<ul>
													<li class="post-date">
														<strong>{{article.day}}</strong>
														<span>{{article.month}}</span>
													</li>
													<li class="post-category"><a href="javascript:void(0);" rel="category tag">Blog</a></li>
													<li class="post-user">By <a href="javascript:void(0);">{{article.author}}</a>
												   </li>
												</ul>
											</div>
											<h3 class="dz-title"><a href="blog-details.html">{{article.title}}</a></h3>
											<div class="dz-post-text text">
												<p>{{article.snippet}}</p>
											</div>
											<div class="read-more">
												<a href="{% url 'blog:detail' article.Url %}" class="btn btn-primary btn-rounded btn-sm hover-icon"><span>Read More </span><i class="fas fa-arrow-right"></i></a>
											</div>
										</div>
									</div>
								</div>
								{% endfor %}
							</div>
						</div>

					</div>
				</div>
		</div>
   </div>

{% endblock %}

Greenmark/home/templates/home/Portfolio.html
{% extends 'base_layout.html' %}
{% load static %}
{% block content %}

<div class="slidearea">
          <div class="side-contact-info">
            <ul>
              <li><i class="fas fa-phone-alt"></i> +91 123 456 7890</li>
              <li><i class="fas fa-envelope"></i> Visvainfo@gmail.com</li>
            </ul>
          </div>
          <div class="silder-one">
            <div class="swiper-container main-silder-swiper">
              <div class="swiper-wrapper">
                <div class="swiper-slide">
                  <div class="silder-img overlay-black-light">
                    <img
                      src="{% static 'images/main-slider/pic1.jpg' %}"
                      data-swiper-parallax="30%"
                      alt=""
                    />
                  </div>
                  <div class="silder-content" data-swiper-parallax="-40%">
                    <div class="inner-content">
                      <h6 class="sub-title">DESIGNING</h6>
                      <h1 class="title">We Create</h1>
                      <h3 class="title-small">
                        Unique Architecture<br />Design Ideas
                      </h3>

                    </div>
                    <div
                      class="overlay-slide"
                      data-swiper-parallax="100%"
                    ></div>
                  </div>
                </div>
                <div class="swiper-slide">
                  <div class="silder-img overlay-black-light">
                    <img
                      src="{% static 'images/main-slider/pic2.jpg' %}"
                      data-swiper-parallax="30%"
                      alt=""
                    />
                  </div>
                  <div class="silder-content" data-swiper-parallax="-40%">
                    <div class="inner-content">
                      <h6 class="sub-title">DESIGNING</h6>
                      <h1 class="title">We Create</h1>
                      <h3 class="title-small">
                        Unique Architecture<br />Design Ideas
                      </h3>

                    </div>
                    <div
                      class="overlay-slide"
                      data-swiper-parallax="100%"
                    ></div>
                  </div>
                </div>
              </div>
              <div class="slider-one-pagination">
                <!-- Add Navigation -->
                <div class="btn-prev swiper-button-prev1 swiper-button-white">
                  <i class="las la-long-arrow-alt-left"></i>PREV
                </div>
                <div class="swiper-pagination swiper-pagination-white"></div>
                <div class="btn-next swiper-button-next1 swiper-button-white">
                  NEXT<i class="las la-long-arrow-alt-right"></i>
                </div>
              </div>
            </div>
          </div>
        </div>
        <!-- Slider End -->
        <!-- Portfolio -->
        <section class="content-inner-1 line-img overflow-hidden pb-5">
          <div class="container">
            <div class="d-flex  site-filters style-1 justify-content-between">
              <ul class="filters" data-toggle="buttons">
                <li class="btn active">
                  <input type="radio" />
                  <a href="javascript:void(0);">All</a>
                </li>
                <li data-filter=".Architecture" class="btn">
                  <input type="radio" />
                  <a href="javascript:void(0);">Architecture</a>
                </li>
                <li data-filter=".Interior.Design" class="btn">
                  <input type="radio" />
                  <a href="javascript:void(0);">Interior Design</a>
                </li>
                <li data-filter=".Construction" class="btn">
                  <input type="radio" />
                  <a href="javascript:void(0);">Construction</a>
                </li>
              </ul>
              <a class="btn btn-primary rounded btn-xs next" href="{% url 'allport:Portfolio' %}" title="more"> View more<i class="fa fa-sm fa-chevron-right"></i></a>

            </div>
          </div>
          <div class="container" >

            <ul id="masonry" class="row lightgallery">
              {% for img in imgs %}
              <li
                class="card-container col-xl-4 col-md-6 col-sm-6 {{img.category}} m-b30"
              >
                <div class="dz-box overlay style-1">
                  <div class="dz-media">
                    <img src="{{img.image.url}}" style="height:600px" alt="" />
                  </div>
                  <div class="dz-info">
                    <span
                      data-exthumbimage="{{img.image.url}}"
                      data-src="{{img.image.url}}"
                      class="view-btn lightimg"
                      title="{{img.category}}"
                    ></span>
                    <h6 class="sub-title">{{img.category}}</h6>
                    <h4 class="title m-b15">
                      <a href="{% url 'allport:portdetail' img.title %}"
                        >{{img.title}}</a
                      >
                    </h4>
                  </div>
                </div>
              </li>
              {% endfor %}
            </ul>

            <div class="d-flex flex-row justify-content-end ">
              <a class="btn btn-primary rounded btn-xs next" href="{% url 'allport:Portfolio' %}" title="more"> View more<i class="fa fa-sm fa-chevron-right"></i></a>
            </div>
          </div>

        </section>
        <!--Contact Us (form and image)-->
        <section
          class="section-full content-inner overflow-hidden pt-5"
          style="
            background-image: url({% static 'images/background/bg1.png' %});
            background-position: left top;
            background-size: 100%;
            background-repeat: no-repeat;
          "
        >
          <div class="container">
            <div class="row align-items-center">
              <div
                class="col-lg-6 m-b30 aos-item"
                data-aos="fade-right"
                data-aos-duration="800"
                data-aos-delay="300"
              >
                <img src="{% static 'images/img1.jpg' %}" alt="" />
              </div>
              <div
                class="col-lg-6 aos-item"
                data-aos="fade-left"
                data-aos-duration="800"
                data-aos-delay="600"
              >
                <div class="section-head style-1">
                  <h6 class="sub-title text-primary">Contact Us</h6>
                  <h2 class="title">Get in touch with us</h2>
                </div>
                <form class="dz-form dzForm contact-bx" method="POST" >
                    {% csrf_token %}
                    <input type="hidden" class="form-control" >
                    <div class="dzFormMsg"></div>
                    <div class="row sp10">
                      <div class="col-12 m-b20">
                        <div class="input-group">
                          <input type="text" class="form-control" required name="name" placeholder="First Name">
                        </div>
                      </div>
                      <div class="col-12 m-b20">
                        <div class="input-group">
                          <input type="email" class="form-control"  name="email" placeholder="Email" pattern="^[^@\s]+@[^@\s]+\.[^@\s]+$">
                        </div>
                      </div>
                      <div class="col-12 m-b20">
                        <div class="input-group">
                          <input type="tel" class="form-control" required name="phonenumber" placeholder="Phone No." pattern="[1-9]{1}[0-9]{9}" >
                        </div>
                      </div>
                      <div class="col-12 m-b20">
                        <div class="input-group">
                          <textarea required name="message" name="dzMessage" rows="5" class="form-control" placeholder="Message"></textarea>
                        </div>
                      </div>
                      <div class="col-12 m-b20">
                        <div class="col-sm-12 text-end">
                          <button name="submit" type="submit" value="submit" class="btn btn-primary btn-rounded">SUBMIT <i class="m-l10 fas fa-caret-right"></i></button>
                        </div>
                      </div>
                    </div>
                </form>
              </div>
            </div>
          </div>
        </section>
        <!--Contact Us-->

{% endblock %}

Greenmark/portfolio/templates/portfolio/allportfolio.html
{% extends 'base_layout.html' %}
{% load static %}
{% block content %}
        <section class="content-inner-1 line-img overflow-hidden">
          <div class="container">
            <div class="site-filters style-1 clearfix center">
              <ul class="filters" data-toggle="buttons">
                <li class="btn active">
                  <input type="radio" />
                  <a href="javascript:void(0);">All</a>
                </li>
                <li data-filter=".Architecture" class="btn">
                  <input type="radio" />
                  <a href="javascript:void(0);">Architecture</a>
                </li>
                <li data-filter=".Interior.Design" class="btn">
                  <input type="radio" />
                  <a href="javascript:void(0);">Interior Design</a>
                </li>
                <li data-filter=".construction" class="btn">
                  <input type="radio" />
                  <a href="javascript:void(0);">Construction</a>
                </li>
              </ul>
            </div>
          </div>
          <div class="container">
            <ul id="masonry" class="row lightgallery">
              {% for images in AllImages%}
              <li
                class="card-container col-xl-4 col-md-6 col-sm-6 {{images.category}} m-b30"
              >
                <div class="dz-box overlay style-1">
                  <div class="dz-media">
                    <img src="{{images.image.url}}" style="height:600px" alt="" />
                  </div>
                  <div class="dz-info">
                    <span
                      data-exthumbimage="{{images.image.url}}"
                      data-src="{{images.image.url}}"
                      class="view-btn lightimg"
                      title="{{images.category}}"
                    ></span>
                    <h6 class="sub-title">{{images.category}}</h6>
                    <h4 class="title m-b15">
                      <a href="{% url 'allport:portdetail' images.title %}"
                        >{{images.title}}</a
                      >
                    </h4>
                  </div>
                </div>
              </li>
              {% endfor %}
            </ul>
          </div>
        </section>
{% endblock %}